name: Bug Report
description: Create a bug report
labels: ["type:bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A concise description of the bug.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which package/app is affected (leave empty if unsure)
      multiple: true
      options:
        - "@neato/guider"
        - "@neato/config"
        - "docs"
        - "examples"
  - type: input
    attributes:
      label: Link to the code that reproduces this issue
      description: |
        If possible, link to a minimal reproducable example. This can be a GitHub gist or a repository, choose whatever fits.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior, please provide a clear description of how to reproduce the issue, based on the linked minimal reproduction. Screenshots can be provided in the issue body below. If using code blocks, make sure that [syntax highlighting is correct](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) and double check that the rendered preview is not broken.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Before submitting, please make sure that the reproduce steps you've provided are easy to follow.
  - type: textarea
    attributes:
      label: Extra details
      description: If you have extra information or a proposal on how to implement it, this is the place.
