name: config - publish version

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    outputs:
      checked: ${{ steps.changed-files.outputs.any_modified }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            packages/config/**

  publish:
    runs-on: ubuntu-latest
    needs: [check]
    if: needs.check.outputs.checked == 'true'
    environment:
      name: npm
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install pnpm packages
      run: pnpm install --frozen-lockfile

    - name: Build
      run: pnpm run build
      working-directory: 'packages/config'

    - name: Publish
      run: pnpm publish --access public
      working-directory: 'packages/config'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
