name: docs - lint and typecheck

on:
  pull_request: {}

jobs:
  check:
    name: Check if files modified
    runs-on: ubuntu-latest
    outputs:
      checked: ${{ steps.changed-files.outputs.any_modified }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            apps/docs/**

  lint:
    name: Linting and Typecheck
    runs-on: ubuntu-latest
    needs: [check]
    if: needs.check.outputs.checked == 'true'
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install pnpm packages
      working-directory: apps/docs
      run: pnpm install --frozen-lockfile

    - name: Build Guider
      run: pnpm run build
      working-directory: 'packages/guider'

    - name: Lint
      working-directory: apps/docs
      run: pnpm lint

    - name: Typecheck
      working-directory: apps/docs
      run: pnpm typecheck
